AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Cross-Region Replication with Encryption and IAM Role
Parameters:
  DestBucket:
    Type: String

Resources:
  s3BucketReplicationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: S3ReplicationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketVersioning
                  - s3:ListBucket
                  - s3:GetObjectVersionAcl
                  - s3:GetObjectVersionTagging
                  - s3:ObjectOwnerOverrideToBucketOwner
                Resource:
                  - !Sub arn:aws:s3:::${AWS::StackName}-sourcebucket-${AWS::AccountId}
                  - !Sub arn:aws:s3:::${AWS::StackName}-sourcebucket-${AWS::AccountId}/*
              - Effect: Allow
                Action:
                  - s3:ReplicateObject
                  - s3:ReplicateDelete
                  - s3:ReplicateTags
                Resource:
                  - !Join
                    - ''
                    - - !Ref DestBucket
                      - /*

  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-sourcebucket-${AWS::AccountId}
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      ReplicationConfiguration:
        Role: !GetAtt s3BucketReplicationRole.Arn
        Rules:
          - Id: s3BucketReplicationRule1
            Status: Enabled
            Prefix: ''
            Destination:
              Bucket: !Ref DestBucket #!Sub "arn:aws:s3:::${AWS::StackName}-destbucket-${AWS::AccountId}"
              StorageClass: STANDARD

  SourceBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SourceBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: RequireEncryptionInTransit
            Effect: Deny
            Principal: '*'
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:ListBucket
            Resource:
              - !Sub arn:aws:s3:::${AWS::StackName}-sourcebucket-${AWS::AccountId}
              - !Sub arn:aws:s3:::${AWS::StackName}-sourcebucket-${AWS::AccountId}/*
            Condition:
              Bool:
                aws:SecureTransport: 'false'

Outputs:
  SourceBucketName:
    Value: !Ref SourceBucket
    Description: Source S3 Bucket Name

  ReplicationRoleArn:
    Value: !GetAtt s3BucketReplicationRole.Arn
    Description: IAM Role ARN for S3 Replication