name: AWS GitHub Actions Test

on: 
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the GitHub Repository
      uses: actions/checkout@v4    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS }}
    - name: Describe ec2 instances
      run: |
       aws ec2 describe-instances
    # - name: Describe ec2 instances
    #   run: |
    #    aws s3 ls       